# Generated by Django 5.2.2 on 2025-06-07 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_days', models.ManyToManyField(to='core.dayofweek')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('up_to_kms', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceAdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_kms', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplierFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_per_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_minutes', models.IntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingconfig')),
            ],
        ),
    ]
